# Generated by Django 6.0 on 2026-10-03 10:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_fingerprint_vector_attendancelog'),
        ('payments', '0003_payment_card_provider_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوردية')),
                ('start_time', models.TimeField(verbose_name='وقت البدء')),
                ('end_time', models.TimeField(verbose_name='وقت الانتهاء')),
                ('overtime_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=10, verbose_name='تكلفة ساعة العمل الإضافي (د.ل)')),
                ('color', models.CharField(default='#3b82f6', max_length=20, verbose_name='لون التمييز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قالب وردية',
                'verbose_name_plural': 'قوالب الورديات',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='extra_duties',
            field=models.TextField(blank=True, null=True, verbose_name='بيان الأعمال والمهام الإضافية'),
        ),
        migrations.AddField(
            model_name='shift',
            name='has_overtime',
            field=models.BooleanField(default=False, verbose_name='يوجد عمل إضافي'),
        ),
        migrations.AddField(
            model_name='shift',
            name='overtime_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='إجمالي تكلفة العمل الإضافي'),
        ),
        migrations.AddField(
            model_name='shift',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='ساعات العمل الإضافي'),
        ),
        migrations.AddField(
            model_name='shift',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='تكلفة الساعة الإضافية'),
        ),
        migrations.AddField(
            model_name='shift',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الانتهاء المجدول'),
        ),
        migrations.AddField(
            model_name='shift',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت البدء المجدول'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_name',
            field=models.CharField(blank=True, default='وردية عادية', max_length=100, verbose_name='اسم الوردية'),
        ),
        migrations.CreateModel(
            name='ShiftAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100, verbose_name='اسم الوردية')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الوردية')),
                ('start_time', models.TimeField(verbose_name='وقت بدء الوردية')),
                ('end_time', models.TimeField(verbose_name='وقت انتهاء الوردية')),
                ('pos_station', models.CharField(default='نقطة البيع الرئيسية (POS 1)', max_length=100, verbose_name='نقطة البيع المخصصة')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('active', 'نشطة / قيد العمل'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='scheduled', max_length=20, verbose_name='حالة الوردية')),
                ('has_overtime', models.BooleanField(default=False, verbose_name='يوجد عمل إضافي')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='ساعات العمل الإضافي')),
                ('overtime_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=10, verbose_name='تكلفة الساعة الإضافية (د.ل)')),
                ('overtime_total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='إجمالي تكلفة العمل الإضافي (د.ل)')),
                ('extra_duties', models.TextField(blank=True, null=True, verbose_name='بيان الأعمال والمهام الإضافية')),
                ('overtime_status', models.CharField(choices=[('none', 'لا يوجد'), ('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('paid', 'تم الصرف')], default='none', max_length=20, verbose_name='حالة اعتماد الإضافي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات عامة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_pos_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='payments.shift', verbose_name='جلسة نقطة البيع الفعلية')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_allocations', to='employees.employee', verbose_name='الموظف')),
                ('shift_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='payments.shifttemplate', verbose_name='قالب الوردية')),
            ],
            options={
                'verbose_name': 'تخصيص وردية',
                'verbose_name_plural': 'تخصيصات الورديات',
                'ordering': ['-date', 'start_time'],
            },
        ),
    ]
