# Generated by Django 6.0 on 2026-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
