# Generated by Django 6.0 on 2026-10-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
