# Generated by Django 6.0 on 2026-10-02 20:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchaseinvoice_supplier_purchaseinvoiceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True, verbose_name='رقم إذن الجرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد والتسوية')),
                ('performed_by', models.CharField(default='المدير', max_length=150, verbose_name='المسؤول عن الجرد')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('APPLIED', 'معتمد وتمت التسوية'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=20, verbose_name='حالة الجرد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('total_system_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة المخزون الدفتري')),
                ('total_actual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة المخزون الفعلي')),
                ('net_variance_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='صافي الفارق المالي')),
                ('total_items_counted', models.IntegerField(default=0, verbose_name='عدد الأصناف المجرودة')),
                ('items_with_shortage', models.IntegerField(default=0, verbose_name='أصناف بها عجز')),
                ('items_with_surplus', models.IntegerField(default=0, verbose_name='أصناف بها زيادة')),
                ('items_matched', models.IntegerField(default=0, verbose_name='أصناف متطابقة')),
            ],
            options={
                'verbose_name': 'إذن جرد',
                'verbose_name_plural': 'أذونات جرد المنتجات والمخزون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_stock', models.FloatField(verbose_name='الرصيد الدفتري المسجل')),
                ('actual_stock', models.FloatField(verbose_name='الرصيد الفعلي بعد العد')),
                ('difference', models.FloatField(verbose_name='الفارق في الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='تكلفة الوحدة')),
                ('variance_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='القيمة المالية للفارق')),
                ('status', models.CharField(choices=[('MATCHED', 'مطابق'), ('SHORTAGE', 'عجز'), ('SURPLUS', 'زيادة')], default='MATCHED', max_length=20, verbose_name='حالة البند')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات البند')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_entries', to='inventory.ingredient')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktake')),
            ],
            options={
                'verbose_name': 'بند إذن جرد',
                'verbose_name_plural': 'بنود أذونات الجرد',
                'ordering': ['id'],
            },
        ),
    ]
