# Generated by Django 6.0 on 2026-10-02 20:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stocktake_stocktakeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=50, unique=True, verbose_name='رقم إذن المرتجع')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي قيمة المرتجع')),
                ('refund_method', models.CharField(choices=[('DEBT_REDUCTION', 'خصم من رصيد ومستحقات المورد'), ('CASH', 'استرداد نقدي (كاش)')], default='DEBT_REDUCTION', max_length=20, verbose_name='طريقة استرداد القيمة')),
                ('reason', models.CharField(default='تالف أو غير مطابق للمواصفات', max_length=255, verbose_name='سبب الإرجاع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('status', models.CharField(choices=[('COMPLETED', 'مكتمل وتم الخصم من المخزون'), ('CANCELLED', 'ملغى')], default='COMPLETED', max_length=20, verbose_name='حالة المرتجع')),
                ('return_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المرتجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='inventory.purchaseinvoice', verbose_name='فاتورة الشراء المرجعية')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='inventory.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'مرتجع شراء',
                'verbose_name_plural': 'مرتجعات الشراء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='الكمية المرتجعة')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر وحدة الإرجاع')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='سبب إرجاع الصنف')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='inventory.ingredient', verbose_name='المادة الخام')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchasereturn', verbose_name='إذن المرتجع')),
            ],
            options={
                'verbose_name': 'بند مرتجع شراء',
                'verbose_name_plural': 'بنود مرتجعات الشراء',
                'ordering': ['id'],
            },
        ),
    ]
