# Generated by Django 6.0 on 2026-09-18 18:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fingerprint_vector',
            field=models.JSONField(blank=True, help_text='مصفوفة ميزات بصمة الإصبع عبر الذكاء الاصطناعي', null=True),
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الحركة')),
                ('punch_type', models.CharField(choices=[('CHECK_IN', 'تسجيل حضور'), ('CHECK_OUT', 'تسجيل انصراف')], default='CHECK_IN', max_length=20, verbose_name='نوع الحركة')),
                ('confidence_score', models.FloatField(help_text='نسبة التطابق المحسوبة بواسطة الذكاء الاصطناعي (0.0 - 1.0)', verbose_name='نسبة الدقة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-timestamp'],
            },
        ),
    ]
