# Generated by Django 6.0 on 2026-09-29 17:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_online_ordering_enabled_restaurantsettings_is_delivery_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='نبذة عن المطعم أو الشعار الترويجي'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='commercial_record',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم صاحب المطعم / المدير'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف إضافي / شكاوى'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم الضريبي'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الموقع الإلكتروني أو صفحة التواصل'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان بالكامل'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='currency',
            field=models.CharField(default='د.ل', max_length=10, verbose_name='العملة الافتراضية'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/', verbose_name='شعار المطعم'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='name',
            field=models.CharField(default='My Restaurant', max_length=255, verbose_name='اسم المطعم'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف الأساسي'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الضريبة'),
        ),
    ]
