# Generated by Django 6.0 on 2026-10-03 10:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restaurantsettings_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان الحسبة / السنة المالية')),
                ('date_calculated', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الحسبة')),
                ('year_type', models.CharField(choices=[('HIJRI', 'حول هجري (2.5%)'), ('GREGORIAN', 'حول شمسي / ميلادي (2.577%)')], default='HIJRI', max_length=15, verbose_name='نوع الحول')),
                ('gold_gram_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='سعر جرام الذهب عيار 24 (د.ل)')),
                ('nisab_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة النصاب (85 جرام ذهب)')),
                ('is_nisab_reached', models.BooleanField(default=True, verbose_name='هل بلغ النصاب')),
                ('cash_in_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='النقدية بالخزينة والصناديق')),
                ('cash_in_bank', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الأرصدة المصرفية')),
                ('inventory_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة البضاعة والمخزون المعد للبيع والتشغيل')),
                ('accounts_receivable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ديون وذمم مرجوة السداد')),
                ('other_zakatable_assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='أصول أخرى خاضعة للزكاة')),
                ('total_assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي الأصول الزكوية')),
                ('accounts_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مستحقات الموردين والديون العاجلة')),
                ('accrued_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مصروفات ورواتب مستحقة')),
                ('other_liabilities', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='خصوم والتزامات أخرى عاجلة')),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي الخصوم الواجب خصمها')),
                ('net_zakat_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='صافي الوعاء الزكوي')),
                ('zakat_percentage', models.DecimalField(decimal_places=3, default=Decimal('2.500'), max_digits=6, verbose_name='نسبة الزكاة المطبقة (%)')),
                ('zakat_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مقدار الزكاة الواجب إخراجها')),
                ('zakat_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الزكاة المدفوعة فعلياً')),
                ('status', models.CharField(choices=[('PENDING', 'مستحقة لم تدفع'), ('PARTIALLY_PAID', 'مدفوعة جزئياً'), ('PAID', 'مدفوعة بالكامل')], default='PENDING', max_length=20, verbose_name='حالة السداد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حسبة زكاة',
                'verbose_name_plural': 'سجل حسابات الزكاة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZakatDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع (د.ل)')),
                ('recipient_category', models.CharField(default='الفقراء والمساكين', max_length=100, verbose_name='مصرف الزكاة (الجهة المستفيدة)')),
                ('recipient_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم المستفيد أو الجمعية')),
                ('disbursed_at', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإخراج')),
                ('payment_method', models.CharField(default='نقداً من الخزينة', max_length=50, verbose_name='طريقة الدفع')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات وسند الصرف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zakat_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='core.zakatcalculation', verbose_name='حسبة الزكاة المرجعية')),
            ],
            options={
                'verbose_name': 'دفعة زكاة',
                'verbose_name_plural': 'دفعات إخراج الزكاة',
                'ordering': ['-disbursed_at'],
            },
        ),
    ]
