# Generated by Django 6.0 on 2026-10-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_zakatcalculation_zakatdisbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='auto_print_on_checkout',
            field=models.BooleanField(default=False, verbose_name='طباعة تلقائية فور الدفع'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='purchase_invoice_template',
            field=models.CharField(default='classic_clean', max_length=50, verbose_name='قالب فاتورة المشتريات'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='purchase_invoice_terms',
            field=models.TextField(blank=True, default='تم فحص واستلام البضاعة بحالة جيدة ومطابقتها لأمر الشراء', null=True, verbose_name='ملاحظات وشروط فاتورة الشراء'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='purchase_return_template',
            field=models.CharField(default='standard_voucher', max_length=50, verbose_name='قالب سند مرتجع الشراء'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='purchase_return_terms',
            field=models.TextField(blank=True, default='يعتبر هذا السند إشعار خصم رسمي معتمد لتسوية حساب المورد', null=True, verbose_name='شروط سند مرتجع المشتريات'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='sales_invoice_template',
            field=models.CharField(default='thermal_80mm', max_length=50, verbose_name='قالب فاتورة المبيعات'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='sales_invoice_terms',
            field=models.TextField(blank=True, default='الأسعار تشمل ضريبة القيمة المضافة إن وجدت • البضاعة المباعة تستبدل خلال 24 ساعة', null=True, verbose_name='شروط وسياسة فاتورة المبيعات'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='show_logo_purchases',
            field=models.BooleanField(default=True, verbose_name='إظهار الشعار في فواتير المشتريات'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='show_logo_returns',
            field=models.BooleanField(default=True, verbose_name='إظهار الشعار في سندات المرتجع'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='show_logo_sales',
            field=models.BooleanField(default=True, verbose_name='إظهار الشعار في فواتير المبيعات'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='show_qr_code',
            field=models.BooleanField(default=True, verbose_name='إظهار رمز الاستجابة السريعة QR Code'),
        ),
    ]
